
#ifndef CONFIGURACION_ALGORITMOS_PLANIFICACION_H_
#define CONFIGURACION_ALGORITMOS_PLANIFICACION_H_

#include <string.h>

#define PLANIFICACION_RR "RR"
#define PLANIFICACION_SJF "SJF"
#define PLANIFICACION_HRRN "HRRN"
#define PLANIFICACION_FIFO "FIFO"

typedef enum {
	FIFO,
	RR,
	HRRN,
	SJF
} t_algoritmo;

#endif /* CONFIGURACION_ALGORITMOS_PLANIFICACION_H_ */
